apiVersion: apps/v1
kind: Deployment
metadata:
  name: indexer-deployment
  labels:
    app: indexer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: indexer
  template:
    metadata:
      labels:
        app: indexer
    spec:
      containers:
        - name: indexer
          image: neonlabsorg/proxy
          command: ["proxy/run-indexer.sh"]
          ports:
            - containerPort: 9090
          env:
            - name: SOLANA_URL
              value: "http://solana-svc:8899"
            - name: POSTGRES_HOST
              value: "postgres-svc"
            - name: POSTGRES_DB
              value: "neon"
            - name: POSTGRES_USER
              value: "neon_proxy"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-password
                  key: password
            - name: CONFIG
              value: "ci"